### ISSUE TITLE
Base de données 

### ISSUE THREAD

**Issue by thiblb** [thiblb/boiteaidees#6]
On utilise quel type de base?

MySQL?  Tu peux la déployer sur ton serveur sans trop de pb? 

Autant on pourra faire notre schéma sql à la volée, autant faut savoir ou est-ce qu'on le déploie

**Comment by thiblb** [comment]
C'est cool mais j'ai deja posé la question avant d'aller manger.

**Comment by landrigun** [comment]
Une instance MySQL c'est pas un soucis sur le serveur.
